### ISSUE TITLE
um it no work on nmy honorx5

### ISSUE THREAD

**Issue by duhpajil** [shawnanastasio/ShawnOS#12]
i was try get shnwos on my hnro5x and it sayed that loadbotter was broken
pls help i rly wnt to use shwnoso n my fone

okthanx

**Comment by drsn0w** [comment]
min e too it doesntwork o nmy nexushonor 5XS Plus Edition

**Comment by duhpajil** [comment]
yae its weird i weas went bac to andoid 6.1.10 and i tryed to tput norton back on but it says it no work so i think am sue shawnso for all theese damagfes

**Comment by vishanand** [comment]
Dupak r dey doin, eye trie 2 enstal et on mi el-gee optimos n it no werk. Et korupt mi jelibeen androyd also

**Comment by duhpajil** [comment]
Shut fukc up veshwish you are retard leqrn some englesh
